version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore Amalgama\Amalgama.sln
build:
  project: Amalgama\Amalgama.sln
  verbosity: minimal
test_script:
- .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:C\:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio\ 14.0/Common7/IDE/MSTest.exe  -targetargs:"/testcontainer:""./Amalgama.PhotoAutoPicker.Tests/bin/Release/Amalgama.PhotoAutoPicker.Tests.dll" -output:.\Amalgama_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "Amalgama_coverage.xml"
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config